# Generated by Django 2.2.10 on 2020-02-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
