# Generated by Django 2.2.10 on 2020-02-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200222_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='name',
            field=models.CharField(default=models.CharField(max_length=50), max_length=50),
        ),
    ]
